// Generated by scripts/build/gen-guardian-logo.py; source: assets/guardian-shield.svg
#pragma once
#include <stdint.h>
#define GUARDIAN_LOGO_W 144
#define GUARDIAN_LOGO_H 144
#ifdef __cplusplus
extern "C" {
#endif
extern const uint16_t GUARDIAN_LOGO_RGB565[144 * 144];
extern const uint8_t GUARDIAN_LOGO_ALPHA[144 * 144 * 3];
#ifdef __cplusplus
}
#endif
